language: cpp

matrix:
  include:
    - os: linux
      dist: bionic

before_install: 
  - git clone https://github.com/google/googletest.git && cd googletest && mkdir build && cd build && cmake .. && make -j8 && sudo make install

before_scrpt:
  - mkdir build && cd build
  - cmake ..

script:
  - make
  - make test